language: python

matrix:
    include:
        - os: linux
          dist: xenial
          python: 3.6
          env: TOXENV=py36
        - os: linux
          dist: xenial
          python: 3.7
          env: TOXENV=py37
        - os: linux
          dist: xenial
          python: nightly
          env: TOXENV=py38
        - os: linux
          dist: xenial
          python: pypy3.5
          env: TOXENV=pypy3
        - os: linux
          dist: trust
          python: 3.6
          env: TOXENV=py36
        - os: linux
          dist: precise
          python: 3.6
          env: TOXENV=py36

install:
  - pip install --upgrade tox

script:
  - tox
